#pragma once
/*
 * Energy dispersal scrambler for DAB (ETSI EN 300 401 §11).
 *
 * A 9-stage linear feedback shift register with polynomial
 *   P(x) = x^9 + x^5 + 1
 * is initialised to all-ones (binary 111111111 = 0x1FF) at the start of each
 * logical frame (for FIC: each FIB; for MSC: each subchannel frame slot).
 *
 * The XOR stream generated by clocking the register is XORed with the input
 * byte stream MSB-first. Scramble and descramble are the same operation.
 */

#include <stddef.h>
#include <stdint.h>

#ifdef __cplusplus
extern "C" {
#endif

typedef struct {
    uint16_t state;   /* 9 bits in the low end */
} prbs9_t;

static inline void prbs9_reset(prbs9_t *p) { p->state = 0x1FF; }

/* Advance the register by one clock and return the output bit (0/1). */
static inline unsigned prbs9_bit(prbs9_t *p) {
    /* Tap positions 9 and 5 → bits [8] and [4] of state. */
    unsigned out = ((p->state >> 8) ^ (p->state >> 4)) & 1u;
    p->state = (uint16_t)(((p->state << 1) | out) & 0x1FFu);
    return out;
}

/*
 * XOR `len` bytes of `in` into `out` using the PRBS9 output clocked 8 bits
 * per byte, MSB first (matches the DAB bit ordering on the wire). Caller is
 * responsible for resetting the register via prbs9_reset before each frame.
 * in and out may alias.
 */
static inline void prbs9_xor(prbs9_t *p, const uint8_t *in, uint8_t *out, size_t len) {
    for (size_t i = 0; i < len; ++i) {
        uint8_t b = in[i];
        uint8_t mask = 0;
        for (int k = 0; k < 8; ++k) {
            mask = (uint8_t)((mask << 1) | prbs9_bit(p));
        }
        out[i] = (uint8_t)(b ^ mask);
    }
}

#ifdef __cplusplus
}
#endif
